[package]
name = "untitled2"
version = "0.1.0"
authors = ["chirichidi <chirichidi@com2us.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd = "0.5"
